// <auto-generated />
using System;
using CAPSquadron_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CAPSquadron_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240706060201_UpperCaseCAPID")]
    partial class UpperCaseCAPID
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CAPSquadron_API.Models.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("AEDateP")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("AEInteractiveDate")
                        .HasColumnType("date");

                    b.Property<string>("AEInteractiveModule")
                        .HasColumnType("text");

                    b.Property<string>("AEModuleOrTest")
                        .HasColumnType("text");

                    b.Property<int?>("AEScore")
                        .HasColumnType("integer");

                    b.Property<string>("AchvName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActivePart")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("ActiveParticipationDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("AprDate")
                        .HasColumnType("date");

                    b.Property<int>("CAPID")
                        .HasColumnType("integer");

                    b.Property<bool>("CadetOath")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("CadetOathDate")
                        .HasColumnType("date");

                    b.Property<string>("CharacterDevelopment")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DrillDate")
                        .HasColumnType("date");

                    b.Property<int?>("DrillScore")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EssayDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("JoinDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("LastModified")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("LeadLabDateP")
                        .HasColumnType("date");

                    b.Property<int?>("LeadLabScore")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("LeadershipExpectationsDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("LeadershipInteractiveDate")
                        .HasColumnType("date");

                    b.Property<string>("NameFirst")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameLast")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("NextApprovalDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("OralPresentationDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("PhyFitTest")
                        .HasColumnType("date");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("SpecialActivityDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("SpeechDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("StaffServiceDate")
                        .HasColumnType("date");

                    b.Property<string>("TechnicalWritingAssignment")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("TechnicalWritingAssignmentDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("UniformDate")
                        .HasColumnType("date");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("WelcomeCourseDate")
                        .HasColumnType("date");

                    b.Property<string>("Wing")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CAPID", "AchvName")
                        .IsUnique();

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("CAPSquadron_API.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CAPID")
                        .HasColumnType("integer");

                    b.Property<bool>("EoCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("Expiration")
                        .HasColumnType("date");

                    b.Property<DateTime?>("InactiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("OpsecCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SafetyCurrent")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CAPID")
                        .IsUnique();

                    b.ToTable("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
