// <auto-generated />
using System;
using CAPSquadron_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CAPSquadron_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240705053133_AddTrackingFields")]
    partial class AddTrackingFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CAPSquadron_API.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CapId")
                        .HasColumnType("integer");

                    b.Property<bool>("EoCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("Expiration")
                        .HasColumnType("date");

                    b.Property<DateTime?>("InactiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("OpsecCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SafetyCurrent")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CapId")
                        .IsUnique();

                    b.ToTable("Members", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
